### PR TITLE
Added teardown() function

### PR DESCRIPTION
**Pull request by callumacrae**

### CODE REVIEW

**Comment by tommoor** [comment]
LGTM 👍 

Highly recommend adding [prettier](https://github.com/prettier/prettier) to your stack btw, the spacing is all over the place in this file and makes it hard to read / review.

**Comment by callumacrae** [comment]
Weird, no idea how that happened - I usually use spaces, not tabs. Fixed, thanks!

I'm using prettier on new projects—and I love it!—but I'm keeping this one tooling-free (hence the ES5) for simplicity.

**Comment by callumacrae** [comment]
Published as both 0.3.0 and 1.0.0 (have been using this long enough in production without any issues), vue-futurelink update will be coming shortly.

**Comment by tommoor** [comment]
I was working on a `react-futurelink` which I'll probably get published sometime over the weekend now this functionality is available 😄

**Pull request merged**
